import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:tala/models/auto.dart';
import 'package:tala/service/data.dart';
import 'package:url_launcher/url_launcher.dart';

class FirstPage extends StatefulWidget {
  FirstPage({Key key}) : super(key: key);

  @override
  _FirstPageState createState() => _FirstPageState();
}

class _FirstPageState extends State<FirstPage> {
  Auto autogenerated;
  Data data = Data();
  
  @override
  void initState() {
    data.fetchData().then((value) {
      setState(() {
        autogenerated = value;
      });
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: const Text('Data'),
      ),
      body: Column(
        children: [
          // ignore: unnecessary_null_comparison
          autogenerated == null
              ? const CircularProgressIndicator()
              : Expanded(
                  flex: 6,
                  child: ListView.builder(
                    
                    itemCount: autogenerated.articles.length ?? 0,
                    itemBuilder: (context, index) => Padding(
                      padding: const EdgeInsets.all(16.0),
                      
                      child: Card(
                        shape: RoundedRectangleBorder(
                          borderRadius:
                              BorderRadius.circular(30), // if you need this
                          side: BorderSide(
                            color: Colors.grey.withOpacity(0.2),
                            width: 1,
                          ),
                        ),
                        elevation: null, // has value when shape is null
                        shadowColor: Colors.black,
                        clipBehavior: Clip.antiAlias,
                        child: Column(
                          children: [
                            ListTile(
                              leading: Icon(Icons.arrow_drop_down_circle),
                              title: Text(
                                  '${autogenerated.articles[index].author}'),
                              subtitle: Text(
                                '${autogenerated.articles[index].source}',
                                style: TextStyle(
                                    color: Colors.black.withOpacity(0.6)),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.all(16.0),
                              child: Text(
                                '${autogenerated.articles[index].description}',
                                style: TextStyle(
                                    color: Colors.black.withOpacity(0.6)),
                              ),
                            ),
                            ButtonBar(
                              alignment: MainAxisAlignment.start,
                             
                              children: [
                                
                                TextButton(
                                  style: ButtonStyle(
                                      backgroundColor:
                                          MaterialStateProperty.all(
                                              Colors.transparent)),
                                              
                                  onPressed: () async {
                                    final url = '${autogenerated.articles[index].url}';
                                    if (await canLaunch(url)) {
                                      await launch(url);
                                    
                                    } else
                                      throw 'Could not launch $url';
                                      

                                    // Perform some action
                                  },
                                  child: const Text('ACTION 1'),
                                ),
                                TextButton(
                                  style: ButtonStyle(
                                      backgroundColor:
                                          MaterialStateProperty.all(
                                              Colors.transparent)),
                                  onPressed: () {
                                    // Perform some action
                                  },
                                  child: const Text('ACTION 2'),
                                ),
                              ],
                            ),
                            Image.network(
                              "${autogenerated.articles[index].urlToImage}",
                              width: double.infinity,
                              height: 300,
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
        ],
      ),
    );
    // ignore: dead_code
  }
}
